runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

liveness_check:
  initial_delay_sec: 500
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

app_start_timeout_sec: 500
